version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    automerge: true
    stability-days: 14
    labels:
      - "dependencies"
      - "rust"
      - "cargo"
