# Configuration for building Rust projects with multiple targets

# Default settings for Windows MSVC toolchain
[target.x86_64-pc-windows-msvc]
linker = "link.exe"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-C", "link-args=-fuse-ld=lld"
]

[target.x86_64-unknown-linux-musl]
linker = "clang"
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",
    "-C", "link-arg=-static",
    "-C", "target-feature=+crt-static"
]

# Global Cargo settings (optional)
[build]
target-dir = "target"  # Define the output directory for build artifacts