name: Code Formatter

on:
  push:
    branches:
      - "*"

jobs:
  format-code:
    name: Format Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Add Rustfmt
        run: rustup component add rustfmt

      - name: Run Cargo Fmt
        run: |
          cargo fmt --all
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Apply rustfmt formatting" || echo "No changes to commit"
          git push origin HEAD
