name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust: [stable, beta, nightly]

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Rust toolchain
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      # Add Clippy Component
      - name: Add Clippy
        run: rustup component add clippy --toolchain ${{ matrix.rust }}

      # Cache Cargo
      - name: Cache Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/bin
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      # Build the project
      - name: Build
        run: cargo build --verbose

      # Run Tests
      - name: Run Tests
        run: cargo test --verbose

      # Run Clippy
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      # Run Formatting Check
      - name: Check Formatting
        run: cargo fmt --all -- --check
